#ifndef MLTOOLKIT_REGRESSION_INTERFACE_REGRESSION_H
#define MLTOOLKIT_REGRESSION_INTERFACE_REGRESSION_H

namespace MLToolkit
{
  namespace Regression
  {
    
  }
}
#endif // MLTOOLKIT_REGRESSION_INTERFACE_REGRESSION_H